// This file is auto-generated by @hey-api/openapi-ts

export type ClientOptions = {
    baseUrl: `${string}://${string}` | (string & {});
};

export type LoginResponse = {
    token: string;
};

export type AdminLoginRequest = {
    email: string;
    password: string;
};

export type AdminSignUpRequest = {
    email: string;
    password: string;
};

export type LoginData = {
    /**
     * Login credentials
     */
    body: AdminLoginRequest;
    path?: never;
    query?: never;
    url: '/admin/login';
};

export type LoginErrors = {
    /**
     * Invalid credentials
     */
    401: string;
};

export type LoginError = LoginErrors[keyof LoginErrors];

export type LoginResponses = {
    /**
     * JWT token for authentication
     */
    200: LoginResponse;
};

export type LoginResponse2 = LoginResponses[keyof LoginResponses];

export type SignupData = {
    /**
     * signup credentials
     */
    body: AdminSignUpRequest;
    path?: never;
    query?: never;
    url: '/admin/signup';
};

export type SignupErrors = {
    /**
     * Server error
     */
    500: string;
};

export type SignupError = SignupErrors[keyof SignupErrors];

export type SignupResponses = {
    /**
     * No content
     */
    204: void;
};

export type SignupResponse = SignupResponses[keyof SignupResponses];
